apiVersion: v1
kind: Namespace
metadata:
  name: cert-fixer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-fixer-account
  namespace: cert-fixer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-fixer-admin-sa-crb
subjects:
  - kind: ServiceAccount
    name: cert-fixer-account
    namespace: cert-fixer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-fixer
  labels:
    app: cert-fixer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-fixer
  template:
    metadata:
      labels:
        app: cert-fixer
    spec:
      serviceAccountName: cert-fixer-account
      containers:
      - name: cert-fixer
        image: alexohneander/cert-fixer:latest
        env:
        - name: INGRESS_SERVICE
          value: ingress-contour-envoy.projectcontour.svc.cluster.local