name: Development

on:
    push:
      tags:
        - '*'
    workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cert-fixer:latest -t ${{ secrets.DOCKER_USERNAME }}/cert-fixer:${{ env.RELEASE_VERSION }} .
    - name: Push Image latest
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cert-fixer:latest
    - name: Push Image version
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cert-fixer:${{ env.RELEASE_VERSION }}